AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-change-detect app

  Simple lambda function that periodically checks a website for changes and notifies user through Slack

Globals:
  Function:
    Timeout: 3

Parameters:
  NotificationNumber:
    Type: Number
    Default: 0031642783886

Resources:
  ChangeDetectFunction:
    Name: Sam-change-detector
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: change_detect/
      Handler: ChangeDetect.lambda_handler
      Runtime: python3.8
      Events:
        Hvdveer5min:
          Type: Schedule
          Properties:
            Name: Hvdveer5min
            Schedule: rate(5 minutes)
            Input: '{"check_type": "hash", "url": "https://www.hvdveer.nl", "unchanged_hash": "015c0f79ba863036c0b08d60f56a5601f65d326961feffd110dce526"}'
        Tuinwijck5min:
          Type: Schedule
          Properties:
            Name: Tuinwijck5min
            Schedule: rate(5 minutes)
            Input: '{"check_type": "hash", "url": "https://www.tuinwijck.nl/huisjes-te-koop/", "unchanged_hash": "22fdeead39caeb2927af2eae610ddccf38da4c669d4dbbc79a150158" }'
        Piccardhof5min:
          Type: Schedule
          Properties:
            Name: Piccardhof5min
            Schedule: cron(*/5 6-22 * * ? *)
            Input: '{"check_type": "html", "url": "https://www.piccardthof.nl/huisjes-te-koop/", "check_line": "<h6>Er zijn op dit moment geen huisjes te koop</h6>",   "original_element": "h6"}'
        ChangeDetect:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          SLACK_WEBHOOK: webhook_secret

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: sms
        Endpoint: !Ref NotificationNumber

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ChangeDetectFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'


Outputs:
  ChangeDetectApi:
    Description: "API Gateway endpoint URL for Prod stage for Website Change Detection function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ChangeDetectFunction:
    Description: "Website Change Detection Lambda Function ARN"
    Value: !GetAtt ChangeDetectFunction.Arn
  ChangeDetectFunctionIamRole:
    Description: "Implicit IAM Role created for Website Change Detection function"
    Value: !GetAtt ChangeDetectFunctionRole.Arn
