AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ChangeDetectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: change_detect/
      Handler: ChangeDetect.lambda_handler
      Runtime: python3.8
      Events:
        Hvdveer5min:
          Type: Schedule
          Properties:
            Name: Hvdveer5min
            Schedule: rate(5 minutes)
            Input: '{"check_type": "hash", "url": "https://www.hvdveer.nl", "unchanged_hash": "015c0f79ba863036c0b08d60f56a5601f65d326961feffd110dce526"}'
        Tuinwijck5min:
          Type: Schedule
          Properties:
            Name: Tuinwijck5min
            Schedule: rate(5 minutes)
            Input: '{"check_type": "hash", "url": "https://www.tuinwijck.nl/huisjes-te-koop/", "unchanged_hash": "8a12e07e53901157e957a72feada52d389f8e6d0f3ccae384c4ce66a" }'
        Piccardhof5min:
          Type: Schedule
          Properties:
            Name: Piccardhof5min
            Schedule: cron(*/5 6-22 * * ? *)
            Input: '{"check_type": "html", "url": "https://www.piccardthof.nl/huisjes-te-koop/", "check_line": "<h6>Er zijn op dit moment geen huisjes te koop</h6>",   "original_element": "h6"}'
        ChangeDetect:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          SLACK_WEBHOOK: webhook_secret

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ChangeDetectApi:
    Description: "API Gateway endpoint URL for Prod stage for Website Change Detection function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ChangeDetectFunction:
    Description: "Website Change Detection Lambda Function ARN"
    Value: !GetAtt ChangeDetectFunction.Arn
  ChangeDetectFunctionIamRole:
    Description: "Implicit IAM Role created for Website Change Detection function"
    Value: !GetAtt ChangeDetectFunctionRole.Arn
